Carlene/mixpanel
ristekoss/ulaskelas-frontend pull request #36
Opened 2023-12-06 14:59 UTC by carlenee

## Thanks for your support to the project. Kindly check and fill below mentioned points

### Detailed description of changes

#### What's New

N/A

#### What's Updated

Mix panel added on these features : 
- Open Calculator
- Add Course on Calculator
- View Course on Calculator
- Add Course Component on Calculator
- Delete Course from Calculator
- Open Profile
- Saved Matkuls from Profile

#### New Package Added

```yaml
"dependencies": 
  - // N / A

"dev_dependencies": 
  - // N / A

```

### Recommendations on how to test the changes

N / A

### Checklist for developer

- [v ] The code builds clean without any errors or warnings
- [v ] The code does not contain commented out code
- [ ] The code does not log anything to console
- [ ] I have added unit test(s) to cover new code and successfully executed ran it
- [ ] I have thoroughly tested the new code and any adjacent features it may affect

### Link to related issue(s)

N / A

### Screenshots or videos (before and after if appropriate)

#### Before

N / A

#### After

N / A

2023-12-06 17:32 UTC, yudha-haris requested changes

2023-12-06 17:32 UTC, yudha-haris commented on lib/features/kalkulator/presentation/pages/kalkulator_page.dart
>                          },
this params isn't suppose to be hardcoded
please refer to the variable, for example

'course_id': calculator.id,
'final_grade': calculator.totalScore,
etc..

2023-12-06 17:32 UTC, yudha-haris commented on lib/features/kalkulator/presentation/pages/komponen_kalkulator_page.dart
> +                      },
this params isn't suppose to be hardcoded
please refer to the variable, for example

'course_id': calculator.id,
'final_grade': calculator.totalScore,
etc..

2023-12-08 14:26 UTC, veloraine commented on lib/features/kalkulator/presentation/pages/komponen_kalkulator_page.dart
> +                      },
regarding the params for the mixpanel event for calculator deletion, use params that available on the calculator component page, on this case:

1. 'course_name': widget.courseName
2. 'final_grade': widget.totalScore
3. 'final_letter_grade': _getFinalScoreAndGrade(widget.totalScore)

2023-12-09 03:44 UTC, yudha-haris approved these changes

2023-12-09 09:59 UTC, yudha-haris commented on lib/features/kalkulator/presentation/pages/kalkulator_page.dart
> +
use switch case instead

2023-12-09 10:01 UTC, yudha-haris commented on lib/features/kalkulator/presentation/pages/komponen_kalkulator_page.dart
> +    }
use switch case instead

if used in multiple pages, consider write in utils

DRY principle = Dont Repeat Yourself

2023-12-09 10:01 UTC, yudha-haris commented on lib/main_page.dart
> +        }
switch (index) {
          case 1:
            MixpanelService.track('open_courses');
          case 2:
            MixpanelService.track('open_klasemen');
          case 3:
            MixpanelService.track('open_calculator');
          case 4:
            MixpanelService.track('open_profile');
        }

2023-12-09 10:02 UTC, yudha-haris commented on lib/main_page.dart
> +        }
use switch case to make code more readable

2023-12-09 10:39 UTC, merged